export const blogs = [
  {
    id: 19,
    title: "Why Sages Wrote Thousands of Hymns for a Reality Beyond Language",
    summary: "When words failed, sages sang. The hidden purpose behind thousands of hymns.",
    tags: ["Spirituality","Philosophy","Psychology","Mythology"],
    source: "Substack",
    link: "https://supersanyam.substack.com/p/why-sages-wrote-thousands-of-hymns?r=ccx8w",
  },
  {
    id: 18,
    title: "Estimate the number of hairs on your scalp?",
    summary: "Welcome to Day 17/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-number-of-hairs-on-your-scalp-cb74a7236713",
  },
  {
    id: 17,
    title: "Estimate the number of Zomato or Swiggy food delivery partners in India",
    summary: "Welcome to Day 16/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-number-of-zomato-or-swiggy-food-delivery-partners-in-india-e2394835ab61",
  },
  {
    id: 16,
    title: "Estimate the number of orders Zomato or Swiggy do in a day",
    summary: "Welcome to Day 15/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-number-of-orders-zomato-or-swiggy-do-in-a-day-7d4ff9c14789",
  },
  {
    id: 15,
    title: "Estimate the number of flights that fly out of Delhi in a Day?",
    summary: "Welcome to Day 14/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-number-of-flights-that-fly-out-of-delhi-in-a-day-83f1c7d18d42",
  },
  {
    id: 14,
    title: "Estimate the revenue of McDonald's outlet from burger sale?",
    summary: "Welcome to Day 13/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-revenue-of-mcdonalds-outlet-from-burger-sale-c1f524c5f0a4",
  },
  {
    id: 13,
    title: "Estimate the number of beers sold in Goa everyday",
    summary: "Welcome to Day 12/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-number-of-beers-sold-in-goa-everyday-6c58d5eb6ac0",
  },
  {
    id: 12,
    title: "Estimate the number of vehicles travelling from Delhi to Gurugram in a day",
    summary: "Welcome to Day 11/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-number-of-vehicles-travelling-from-delhi-to-gurugram-in-a-day-3ce19c71484c",
  },
  {
    id: 11,
    title: "Estimate the number of iPhone users currently in India",
    summary: "Welcome to Day 10/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-number-of-iphones-users-currently-in-india-39c0d7ab1310",
  },
  {
    id: 10,
    title: "Estimate the number of Harry Potter books sold this year in India",
    summary: "Welcome to Day 9/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-number-of-harry-potter-books-sold-this-year-in-india-e475e5731a23",
  },
  {
    id: 9,
    title: "Estimate the market share of pencils",
    summary: "Welcome to Day 8/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-market-share-of-pencils-432b774e3e94",
  },
  {
    id: 8,
    title: "Estimate the market size of eyewear for vehicle owners in Delhi",
    summary: "Welcome to Day 7/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-market-size-of-eyewear-for-vehicle-owners-in-delhi-257f9b68f20c",
  },
  {
    id: 7,
    title: "Estimate the number of cars in Delhi",
    summary: "Welcome to Day 6/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-number-of-cars-in-delhi-36868408adb9",
  },
  {
    id: 6,
    title: "Calculate the number of queries answered by Google per second",
    summary: "Welcome to Day 5/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-calculate-the-number-of-queries-answered-by-google-per-second-bccc0c242a6",
  },
  {
    id: 5,
    title: "Estimate the number of Uber Drivers in Delhi",
    summary: "Welcome to Day 4/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-number-of-uber-drivers-in-delhi-3156319224a9",
  },
  {
    id: 4,
    title: "Estimate the number of trees in Delhi",
    summary: "Welcome to Day 3/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-number-of-trees-in-delhi-32e63451163",
  },
  {
    id: 3,
    title: "Estimate the Facebook Users in India",
    summary: "Welcome to Day 2/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-facebook-users-in-india-46031fa41583",
  },
  {
    id: 2,
    title: "Estimate the number of schools in Delhi",
    summary: "Welcome to Day 1/30 of Mastering Guesstimates",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimate-estimate-the-number-of-schools-in-delhi-d994fdb394ac",
  },
  {
    id: 1,
    title: "Guide to Guesstimates",
    summary: "Guesstimates - Why, What & How?",
    tags: ["Guesstimates"],
    source: "Medium",
    link: "https://supersanyam.medium.com/guesstimates-why-what-how-79cff27daa90",
  },
];
